orbs:
  python: circleci/python@1.4.0

version: 2.1

jobs:
  install:
    machine:
      image: ubuntu-1604:201903-01

    steps:
      - checkout
      
      - run:
          command: |
            python --version
            pyenv versions

      - run:
          name: Install docker-squash
          command: |
            pip3 install docker==4.4.4
            pip3 install docker-squash
          

workflows:
  build:
    jobs:
      - install