orbs:
  python: circleci/python@1.4.0

version: 2.1

jobs:
  install:
    executor: python/default
    steps:
      - checkout
      
      - run:
          command: |
            python --verstion

      - run:
          name: Install docker-squash
          command: |
            pip install docker==4.4.4
            pip install docker-squash
          

workflows:
  build:
    jobs:
      - install